# Generated by Django 4.2.1 on 2023-06-05 18:28

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_remove_score_score_remove_score_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='parameters',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
