# Generated by Django 4.2.1 on 2023-06-05 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0007_alter_judge_data'),
        ('scores', '0003_alter_score_parameters'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('participant', 'judge')},
        ),
    ]
