# Generated by Django 4.2.1 on 2023-06-05 18:30

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_alter_score_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='parameters',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
    ]
