# Generated by Django 4.2.1 on 2023-06-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_alter_score_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
