# Generated by Django 4.2.1 on 2023-06-18 20:44

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0008_alter_score_parameters_alter_score_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='parameters',
            field=jsonfield.fields.JSONField(default='{"p1": 0, "p2": 0, "p3": 0, "p4": 0, "p5": 0, "p6": 0, "p7": 0, "p8": 0, "p9": 0, "p10": 0}'),
        ),
    ]
