# Generated by Django 4.2.1 on 2023-06-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0010_alter_score_parameters_alter_score_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
