# Generated by Django 4.2.1 on 2023-06-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0011_score_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='status',
        ),
    ]
