# Generated by Django 4.2.1 on 2023-06-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0005_remove_participant_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='drive_file_id',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='file_uploaded',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='ppt',
        ),
    ]
