# Generated by Django 4.2.1 on 2023-06-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0006_remove_participant_drive_file_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
