# Generated by Django 4.2.1 on 2023-06-19 07:48

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0007_alter_judge_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='data',
        ),
        migrations.AddField(
            model_name='judge',
            name='startups_judged',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
    ]
