# Generated by Django 4.2.9 on 2024-01-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0010_participant_rank_participant_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='panel_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
