# Generated by Django 4.2.9 on 2024-01-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0011_judge_panel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='num_judges_with_zero',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
