# Generated by Django 4.2.9 on 2024-01-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0012_participant_num_judges_with_zero'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='panel_id',
            field=models.IntegerField(default=0),
        ),
    ]
